version: '2'
services:
  config-service:
    container_name: configuration-service
    build:
      context: configuration-service
      dockerfile: Dockerfile
    image: configuration-service:latest
    ports:
      - 8888:8888
    environment:
      NAME: config-service
    networks:
      - spring-cloud-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  spring-cloud-network:
    driver: bridge